"""
Prompts for every feature module, engineered to be TOKEN-EFFICIENT.

Why they are compact
  * Every request pays for input tokens (persona + schema + document) and output
    tokens (the JSON the model writes). Both are trimmed here:
      - short persona, compact schema instead of prose descriptions
      - explicit length limits and item caps so the model stops early
      - minified JSON requested (no indentation whitespace)
      - the fixed legal disclaimer is NOT generated by the model; the server adds it
        (see DISCLAIMERS) - generating a constant sentence is pure wasted output.

`MAX_TOKENS` holds a per-feature output ceiling (a safety net, not a target).
"""

SYSTEM_PERSONA = (
    "You are LexAI, a legal-document analyst. Reply with ONLY minified JSON matching the "
    "schema below - no markdown, no extra text. Cite clause/section numbers where possible. "
    "Be concise and plain-spoken. You give general information, not legal advice. "
    "If the text is not a legal document, still answer in the schema."
)

# Fixed sentences added by the server after generation (never generated by the model).
DISCLAIMERS = {
    "simplify": "This simplification is for informational purposes only and does not constitute legal advice. Please consult a qualified legal professional for advice specific to your situation.",
    "risk": "This risk analysis is for informational purposes only and does not constitute legal advice. Please consult a qualified legal professional before signing any document.",
    "compare": "This comparison is for informational purposes only and does not constitute legal advice. Please consult a qualified legal professional before signing any document.",
    "qna": "This answer is based solely on the provided document and is for informational purposes only. It does not constitute legal advice. Please consult a qualified legal professional for guidance specific to your situation.",
    "next_steps": "This information is for general educational purposes only and does not constitute legal advice. Laws vary by jurisdiction and individual circumstances. Please consult a qualified legal professional before taking any action.",
    "summary": "This summary is for informational purposes only and does not constitute legal advice. Always review the full document and consult a qualified legal professional.",
    "lawyer_prep": "This preparation guide is for informational purposes only. It does not constitute legal advice. Only a licensed attorney who reviews your specific situation can provide legal advice.",
}

# Output-token ceilings per feature. Expected outputs are well below these.
MAX_TOKENS = {
    "simplify": 1000,
    "risk": 1400,
    "compare": 1400,
    "qna": 700,
    "next_steps": 1100,
    "summary": 1200,
    "lawyer_prep": 1200,
}

# ─── 1. Document Simplifier ────────────────────────────────────────────────────

SIMPLIFY_PROMPT = """{system}

TASK: Explain this legal document in plain English for a non-lawyer.

DOCUMENT:
\"\"\"
{document}
\"\"\"

Schema:
{{"plain_summary":"120-180 words: what it is, who is involved, what it means for each party","key_terms":[{{"term":"","definition":"plain-English meaning as used here, under 25 words"}}],"reading_level":"Elementary|Middle School|High School|College","document_type":"Contract|Agreement|Policy|Statute|Court Order|Lease|Will|NDA|Terms of Service|Other: <type>"}}
Rules: 5-8 key_terms, only the most important.
"""

# ─── 2. Risk & Clause Highlighter ─────────────────────────────────────────────

RISK_PROMPT = """{system}

TASK: Find the clauses in this legal document that could hurt the reader's interests.

DOCUMENT:
\"\"\"
{document}
\"\"\"

Schema:
{{"document_type":"Contract|Agreement|Policy|Lease|NDA|Terms of Service|Other: <type>","overall_risk":"HIGH|MEDIUM|LOW","risk_clauses":[{{"clause_text":"quote or paraphrase, max 25 words","risk_level":"HIGH|MEDIUM|LOW","risk_reason":"why it is risky and the impact, max 30 words","page_reference":"section/clause number or null"}}],"obligations":["specific obligation of the reader, max 20 words"],"inconsistencies":["contradiction or ambiguity, max 25 words"]}}
Rules: overall_risk = the highest clause risk (LOW if none). Up to 8 risk_clauses, worst first. Up to 6 obligations. Up to 3 inconsistencies ([] if none).
"""

# ─── 3. Contract Comparison ────────────────────────────────────────────────────

COMPARE_PROMPT = """{system}

TASK: Compare these two legal documents.

DOCUMENT A ({label_a}):
\"\"\"
{document_a}
\"\"\"

DOCUMENT B ({label_b}):
\"\"\"
{document_b}
\"\"\"

Schema:
{{"summary":"2 sentences: key differences and which is more favorable to the reader","differences":[{{"category":"Payment Terms|Termination|Liability|Confidentiality|IP Rights|Governing Law|Duration|Other: <x>","document_a_text":"max 20 words","document_b_text":"max 20 words","significance":"HIGH|MEDIUM|LOW","notes":"practical impact, max 25 words"}}],"missing_in_a":["important clause only in B"],"missing_in_b":["important clause only in A"],"recommendation":"specific and actionable, max 60 words"}}
Rules: up to 8 differences, most significant first. Up to 4 items in each missing list ([] if none).
"""

# ─── 4. Legal Q&A ─────────────────────────────────────────────────────────────

QNA_PROMPT = """{system}

TASK: Answer the question using ONLY the document{scope} below. If the document does not address it, say so.

DOCUMENT:
\"\"\"
{document}
\"\"\"

QUESTION: {question}

Schema:
{{"answer":"direct plain-language answer, max 80 words","source_clause":"short direct quote (max 40 words) supporting the answer, or empty string","confidence":"HIGH|MEDIUM|LOW","caveat":"one short caveat or exception, or empty string"}}
Rules: HIGH = clearly stated; MEDIUM = needs interpretation; LOW = not directly addressed. Never invent facts. If unanswerable, answer "The provided document does not address this question."
"""

# Inserted into {scope} when a long document has been reduced to relevant excerpts.
QNA_EXCERPT_SCOPE = " (relevant excerpts of a longer document; [...] marks omitted text - if the excerpts do not cover the question, say so with LOW confidence)"

# ─── 5. Options & Next Steps ──────────────────────────────────────────────────

NEXT_STEPS_PROMPT = """{system}

TASK: Give a neutral overview of the legal options and practical next steps for this situation.

SITUATION:
\"\"\"
{situation}
\"\"\"

JURISDICTION: {jurisdiction}

Schema:
{{"situation_summary":"1-2 sentences","legal_options":["plain-language option, max 25 words"],"next_steps":[{{"step_number":1,"action":"short title","description":"1-2 sentences on what to do and why","urgency":"IMMEDIATE|SHORT_TERM|LONG_TERM"}}],"important_notes":["deadline or warning, max 25 words"]}}
Rules: 3-5 legal_options. Up to 6 next_steps, IMMEDIATE first, one of them consulting a qualified attorney. Up to 4 important_notes including time limits. Tailor to the jurisdiction if one is given.
"""

# ─── 6. Summary & Checklist Generator ─────────────────────────────────────────

SUMMARY_PROMPT = """{system}

TASK: Produce an executive summary and action checklist for this legal document.

DOCUMENT:
\"\"\"
{document}
\"\"\"

Schema:
{{"document_type":"Contract|Agreement|Policy|Lease|NDA|Terms of Service|Other: <type>","executive_summary":"120-180 words: what it is, the parties, main terms, key rights and restrictions","key_parties":["name - role"],"key_dates":["date or period - what it is"],"key_obligations":["party: obligation"],"checklist":[{{"item":"action, max 15 words","done":false,"priority":"HIGH|MEDIUM|LOW"}}]}}
Rules: up to 5 key_parties, 8 key_dates, 8 key_obligations, 8 checklist items. Priority HIGH = do before signing, MEDIUM = during the term, LOW = optional.
"""

# ─── 7. Lawyer Prep Assistant ─────────────────────────────────────────────────

LAWYER_PREP_PROMPT = """{system}

TASK: Prepare the user for a consultation with a lawyer.

SITUATION:
\"\"\"
{situation}
\"\"\"

DOCUMENT (if any):
\"\"\"
{document}
\"\"\"

Schema:
{{"case_summary":"2-3 sentences the user can read out to the lawyer","documents_to_bring":["specific document or evidence"],"questions":[{{"category":"Rights & Obligations|Timeline|Costs & Fees|Strategy|Risks|Evidence|Settlement|Other: <x>","question":"specific to this situation","why_important":"max 15 words"}}],"red_flags":["serious concern and why, max 25 words"]}}
Rules: 8 questions specific to this situation (not generic), grouped by category. Up to 6 documents_to_bring (specific, not "relevant documents"). Up to 4 red_flags.
"""
